language: android

install: true

sudo: true

notifications:
  email: false

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # BuildTools version used by project
    - build-tools-26.0.2

    # SDK version to compile project
    - android-26

script: ./deploy.sh

before_install:
  - openssl aes-256-cbc -K $encrypted_ef3ee9c28dcc_key -iv $encrypted_ef3ee9c28dcc_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - gem install fastlane supply

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
