language: android

install: true

sudo: true

notifications:
  email: false

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools # duplicated on purpose as it’s required to get the newest Android SDK tools.

    # BuildTools version used by project
    - build-tools-26.0.2

    # SDK version to compile project
    - android-26

before_install:
  - openssl aes-256-cbc -K $encrypted_cfd0276aa3e8_key -iv $encrypted_cfd0276aa3e8_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - gem install fastlane supply
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g. avdmanager)
  - sdkmanager tools
  # Install the system image.
  - sdkmanager "system-images;android-24;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n emulatorApi24 -k "system-images;android-24;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd emulatorApi24 -no-audio -no-window &

before_script:
  - android-wait-for-emulator
  # Disable animations
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script: "./deploy.sh"

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
  - ".gradle"

env:
  global:
  - secure: lsaw9Tm04tFe0+KDu5aao/Q+mszvaqT7HDlxuuttB4hDYMWyIlsYEz3vFU81JZvSqFDtM+bMkAzIjdWeqQ1WBZqY1yE/IuNNaPgpsIuwyg2GheroufcLj2Q0Rpa0mrSVoL/NbxS3xwjclHpRwjiPKkQTB/9UHIiyKtPo1wkISsc7T5Yys7ACT6V7T9Ndw9RFALL5Ws6ypgXuBX13i8JzmO4ZSedq6nWlxsyNl0pdfJNKihX5079pvUZb/63TL3o72iePPV9rJnjZHkz1g5qAyO5tMTGXHnI6UB89Zzx/19EnUmrxi3HgCivaq1c3iyFdFmFI9TDCmBgkz4rZ5R8B4ju8ic9zFr66CP29eGiOKUTKSo9ZperCRJcBOAoDz/aXtdjBVgaeG4nGB9pr8Ix0g601QHlvKI6oBtq/xEnk1PesmWuUE5lKNDeF4w9jvv7rrJKqSKlvjSJs1DkIrFMhiWx/NYjbvuJxpJBuJLG0Q6w48UbRtRDAdlfcI/ZnrnsrqBZdS01J/xCB4zFP28ZGnTI2Ow1nYAWuUpswjo+DLeuzCTWCA2iQ10ptGp2rJusQQFRRzBWuiS+KuLb5Rs2BFV6XmcL3FXGXWk/6sJ1awaZ4YjREe5rStL1QCkoQ60nl1UKXUZzFeUZ39riEq6O6ynhaq+ukbKxixzOKW2EsBPs=
  - secure: alw5VIlh8TYZb7PSQqV7+x6w5tGs07qZnA5z65E9RCxxxUP+sMp43GuFwvxKV2Ds0y/QUwE5Now9nGaHt1jlaYa4gw27KmVX1+GafjT3t3GLnovb4bxc0XcraIUVOWGF/Yxz93ps9EPM8ATLEAmjZP1kBl4UhzTrRsJnbS4/FJReo9OtcqoITa2SjVgnUCdFGPKWtJd+d4ZYkiYL2T/IHjHP+D7eENB1iPLYx/0SrpvcaGaAwyvX76tYO0gtkaymCbXepK++VnPOOBx/VT2XAjmqLY362kKx67HdfVOflREd60IAfx4V91CGlEnNnn18wPzi8Yjoif/SmXgItJofNFGCnbvhcWrubCxz8yNzx4j6KSroSJqkm9YPP9JodF5ThnguPuz+kJs7m4iRIA4i3WycedQ3V4GYWdG9JRXY+rEShWKPQ2jSlR232KkXlXGT6X2pzdSwKw4lOw+MTr+77jWvI8amq5VlEc/kHq7Ve1dOVNFsAs/iVdc8A/UNnXRl3OeDjbEZVyTQKhNWvkfCs7A7wjnWtBgKTfMG6p8tBYyb1U16Kxl0mY9iaKj+E/imOgW4kxL2tpRJeUKOwxnJH7h7sGH7BuOknXeaEYMbxhb0o11fNrBEh72tZw0OF0rK9l1fiv8x6Oxkc6lK8bC93TAGC6zYzr8unxOrxIbLqc8=
  - secure: n4g4Q15m429VSR6gZmgQP6lZ8imH4W5eQ9+vLaH7+WOqm1VobxEusEInjuqkdl8cqDnBGkKPuzn5QevD9NXBUGlbHgRt2MyxcKPeZFKat5uE5JUjg1yPiizGtqdEBFAUCE/GmGP+N7uGXL1AJxyQdDvaBRZB/tHE7qlyqfGl4hGaFLNc0DQgO45pmruGQ7ysYj3Bfgs9l6uHc8W7i0MBd1F1hce1Fp3atnwEszHXNCH17+R5fOXLJe8kpa40g7bvUfqZtU4IrwmK73B6y/4eEKuAP7CZYNRGjFmnh0SYtXrNPm3WMzSlffjZM5WN0PVbZgBGPJbhhFcTOZEp6enJmA2tKhBTFCMNj79YyuXSMmYqIlYcl6KRZsPbOj5IZfpg11kYK1JFeAx5k3cX4uw8f1QVne3ZlC3qNGA1dgK+k2GNXbdGQBjRs1GTYE7g+kS1X2+1d7L8OozDLddpIKscdxOz8Mn44SWDTcdmpbT50fzaM15zKynyU1Z5yiWunXjp4r2yAjBZWiHr7Nv6/VjTHu+Xd+VXuPzMWLMelpXT7mxX3PuTwDto1l+Fb1/kfbAttv0s5zsWuU5qYi9OXbIAV30riIhv+ZjRL3Xats3aphU7GrTrJeGEwcJCM5D5h1keVtlBep3PhqaZsNJPsRImbjUywvPXP/wE7WzkzlqYlPY=
